import { Router, Response } from 'express';
import multer from 'multer';
import sharp from 'sharp';
import { getSupabaseAdminClient } from '../lib/supabase';
import { authenticate } from '../middleware/auth';
import { validateId } from '../middleware/security';
import { AuthRequest, ApiResponse } from '../types';
import logger from '../lib/logger';
import {
  detectAndEncode,
  findBestMatch,
  isModelsLoaded,
  StudentEncoding,
} from '../lib/faceRecognition';

const router = Router();

// Multer for image uploads (memory storage — we process the buffer directly)
const storage = multer.memoryStorage();
const upload = multer({
  storage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB
  fileFilter: (_req, file, cb) => {
    if (file.mimetype.startsWith('image/')) {
      cb(null, true);
    } else {
      cb(new Error('Only image files are allowed'));
    }
  },
});

/* ==============================================
   POST /api/face/match
   Server-side face recognition:
   1. Decode the uploaded image
   2. Detect face & compute 128-d descriptor
   3. Fetch all student encodings from DB
   4. Find best Euclidean-distance match
   5. Return matched student with confidence
   ============================================== */
router.post(
  '/match',
  authenticate,
  upload.single('image'),
  async (req: AuthRequest, res: Response): Promise<void> => {
    try {
      if (!req.file) {
        const response: ApiResponse = { success: false, error: 'No image file provided' };
        res.status(400).json(response);
        return;
      }

      // Step 1: Client securely encodes the face in the browser using WebGL!
      logger.info('Processing fast matching request from pre-computed client descriptor...');
      
      let queryDescriptor: Float32Array | null = null;
      if (req.body.face_encoding) {
        try {
          const parsed = JSON.parse(req.body.face_encoding);
          queryDescriptor = new Float32Array(parsed);
        } catch (e) {
          logger.warn('Failed to parse face encoding array from client string', e);
        }
      }

      if (!queryDescriptor) {
        const response: ApiResponse = {
          success: false,
          error: 'No valid face encoding array was generated by your browser scanner.',
        };
        res.status(422).json(response);
        return;
      }

      // Step 2: Fetch all students with face encodings from DB
      const supabase = getSupabaseAdminClient();
      const { data: encodings, error: dbError } = await supabase
        .from('students')
        .select('id, face_encoding')
        .not('face_encoding', 'is', null)
        .eq('teacher_id', req.user!.id); // Only match against this teacher's students

      if (dbError) throw dbError;

      if (!encodings || encodings.length === 0) {
        const response: ApiResponse = {
          success: false,
          error: 'No students with face data found. Add student photos first to enable face recognition.',
        };
        res.status(404).json(response);
        return;
      }

      // Step 3: Find best match
      const match = findBestMatch(queryDescriptor, encodings as StudentEncoding[]);

      if (!match) {
        const response: ApiResponse = {
          success: false,
          error: 'No matching student found in the database.',
          data: { scannedStudents: encodings.length },
        };
        res.status(404).json(response);
        return;
      }

      // Step 4: Fetch full student details for the match
      const { data: student, error: studentError } = await supabase
        .from('students')
        .select('*, classes(*), departments(*)')
        .eq('id', match.studentId)
        .single();

      if (studentError || !student) {
        const response: ApiResponse = { success: false, error: 'Matched student record not found.' };
        res.status(404).json(response);
        return;
      }

      logger.info(`Face matched: ${student.name} (confidence: ${match.confidence}%, distance: ${match.distance.toFixed(4)})`);

      const response: ApiResponse = {
        success: true,
        data: {
          student,
          confidence: match.confidence,
          distance: match.distance,
          scannedStudents: encodings.length,
        },
        message: `Student identified with ${match.confidence}% confidence`,
      };
      res.status(200).json(response);
    } catch (error) {
      logger.error('Face match error:', error);
      const errorMessage = error instanceof Error ? error.message : String(error);
      const response: ApiResponse = { success: false, error: `Processing failed: ${errorMessage}` };
      res.status(500).json(response);
    }
  }
);

/* ==============================================
   GET /api/face/encodings
   Returns all students with face encodings
   (used for stats / admin view)
   ============================================== */
router.get('/encodings', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const supabase = getSupabaseAdminClient();

    const { data: students, error } = await supabase
      .from('students')
      .select('id, name, roll_number, face_encoding, profile_image_url')
      .not('face_encoding', 'is', null)
      .eq('teacher_id', req.user!.id);

    if (error) throw error;

    const response: ApiResponse = { success: true, data: students || [] };
    res.status(200).json(response);
  } catch (error) {
    logger.error('Get encodings error:', error);
    const response: ApiResponse = { success: false, error: 'Failed to fetch face encodings' };
    res.status(500).json(response);
  }
});

/* ==============================================
   POST /api/face/encoding/:studentId
   Manually update a student's face encoding
   from a provided Float32Array (for admin use)
   ============================================== */
router.post(
  '/encoding/:studentId',
  authenticate,
  validateId('studentId'),
  async (req: AuthRequest, res: Response): Promise<void> => {
    try {
      const { studentId } = req.params;
      const { encoding } = req.body;

      if (!encoding || !Array.isArray(encoding)) {
        const response: ApiResponse = { success: false, error: 'Valid face encoding array is required' };
        res.status(400).json(response);
        return;
      }

      const supabase = getSupabaseAdminClient();
      const { data: student, error } = await supabase
        .from('students')
        .update({ face_encoding: encoding })
        .eq('id', studentId)
        .eq('teacher_id', req.user!.id)
        .select()
        .single();

      if (error) throw error;

      const response: ApiResponse = { success: true, data: student, message: 'Face encoding stored successfully' };
      res.status(200).json(response);
    } catch (error) {
      logger.error('Store encoding error:', error);
      const response: ApiResponse = { success: false, error: 'Failed to store face encoding' };
      res.status(500).json(response);
    }
  }
);

/* ==============================================
   POST /api/face/encode-image/:studentId
   Upload an image, encode the face, and update
   the student's face_encoding in the DB
   ============================================== */
router.post(
  '/encode-image/:studentId',
  authenticate,
  validateId('studentId'),
  upload.single('image'),
  async (req: AuthRequest, res: Response): Promise<void> => {
    try {
      if (!req.file) {
        const response: ApiResponse = { success: false, error: 'No image file provided' };
        res.status(400).json(response);
        return;
      }

      // Direct Client Mapping 
      let descriptor: Float32Array | null = null;
      if (req.body.face_encoding) {
        try {
          const parsed = JSON.parse(req.body.face_encoding);
          descriptor = new Float32Array(parsed);
        } catch (e) {
          logger.warn('Failed to parse face encoding array from client string in encode-image', e);
        }
      }

      if (!descriptor) {
        const response: ApiResponse = { success: false, error: 'No valid pre-computed face encoding array found in the client request.' };
        res.status(422).json(response);
        return;
      }

      const supabase = getSupabaseAdminClient();
      const { data: student, error } = await supabase
        .from('students')
        .update({ face_encoding: Array.from(descriptor) })
        .eq('id', req.params.studentId)
        .eq('teacher_id', req.user!.id)
        .select()
        .single();

      if (error) throw error;

      const response: ApiResponse = {
        success: true,
        data: student,
        message: 'Face encoding computed and saved successfully',
      };
      res.status(200).json(response);
    } catch (error) {
      logger.error('Encode image error:', error);
      const response: ApiResponse = { success: false, error: 'Failed to encode face from image' };
      res.status(500).json(response);
    }
  }
);

/* ==============================================
   DELETE /api/face/encoding/:studentId
   Clear a student's face encoding
   ============================================== */
router.delete(
  '/encoding/:studentId',
  authenticate,
  validateId('studentId'),
  async (req: AuthRequest, res: Response): Promise<void> => {
    try {
      const { studentId } = req.params;
      const supabase = getSupabaseAdminClient();

      const { error } = await supabase
        .from('students')
        .update({ face_encoding: null })
        .eq('id', studentId)
        .eq('teacher_id', req.user!.id);

      if (error) throw error;

      const response: ApiResponse = { success: true, message: 'Face encoding deleted successfully' };
      res.status(200).json(response);
    } catch (error) {
      logger.error('Delete encoding error:', error);
      const response: ApiResponse = { success: false, error: 'Failed to delete face encoding' };
      res.status(500).json(response);
    }
  }
);

export default router;
